// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBWtfI0cpGpO904WpDpKx1PqICAhEkgDXY",
    authDomain: "sporticturfs.firebaseapp.com",
    projectId: "sporticturfs",
    storageBucket: "sporticturfs.firebasestorage.app",
    messagingSenderId: "796490347198",
    appId: "1:796490347198:web:f7b79acc3f22b86eaca4ef",
    measurementId: "G-34XE2DQ0HG",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWveCTbmB2aRcB-uqnOsIocZv7xqce4U',
    appId: '1:796490347198:android:eae3be2da137b691aca4ef',
    messagingSenderId: '796490347198',
    projectId: 'sporticturfs',
    storageBucket: 'sporticturfs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iPJsXyqO0LyaR5GNQvvqns16aNCtzLo',
    appId: '1:796490347198:ios:adad63d717462907aca4ef',
    messagingSenderId: '796490347198',
    projectId: 'sporticturfs',
    storageBucket: 'sporticturfs.firebasestorage.app',
    androidClientId:
        '796490347198-17mg4qbu1oc6ggj1i9ki29lsgahkp50a.apps.googleusercontent.com',
    iosClientId:
        '796490347198-5aue58g2k7ajqua7b1uukb1cns1k25d9.apps.googleusercontent.com',
    iosBundleId: 'com.sport.sports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iPJsXyqO0LyaR5GNQvvqns16aNCtzLo',
    appId: '1:796490347198:ios:adad63d717462907aca4ef',
    messagingSenderId: '796490347198',
    projectId: 'sporticturfs',
    storageBucket: 'sporticturfs.firebasestorage.app',
    androidClientId:
        '796490347198-17mg4qbu1oc6ggj1i9ki29lsgahkp50a.apps.googleusercontent.com',
    iosClientId:
        '796490347198-5aue58g2k7ajqua7b1uukb1cns1k25d9.apps.googleusercontent.com',
    iosBundleId: 'com.sport.sports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWtfI0cpGpO904WpDpKx1PqICAhEkgDXY',
    appId: '1:796490347198:web:ac66049abe1d363aaca4ef',
    messagingSenderId: '796490347198',
    projectId: 'sporticturfs',
    authDomain: 'sporticturfs.firebaseapp.com',
    storageBucket: 'sporticturfs.firebasestorage.app',
    measurementId: 'G-FCEQZ7XSMQ',
  );
}
